CREATE TABLE card_model
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255),
    description   VARCHAR(255),
    family        VARCHAR(255),
    affinity      VARCHAR(255),
    img_url       VARCHAR(255),
    small_img_url VARCHAR(255),
    energy        FLOAT                                    NOT NULL,
    hp            FLOAT                                    NOT NULL,
    defence       FLOAT                                    NOT NULL,
    attack        FLOAT                                    NOT NULL,
    price         FLOAT                                    NOT NULL,
    user_id       INTEGER,
    store_id      INTEGER,
    CONSTRAINT pk_cardmodel PRIMARY KEY (id)
);

CREATE TABLE card_reference
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255),
    description   VARCHAR(255),
    family        VARCHAR(255),
    affinity      VARCHAR(255),
    img_url       VARCHAR(255),
    small_img_url VARCHAR(255),
    CONSTRAINT pk_cardreference PRIMARY KEY (id)
);

CREATE TABLE store_transaction
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id  INTEGER,
    card_id  INTEGER,
    store_id INTEGER,
    amount   FLOAT                                    NOT NULL,
    action   SMALLINT,
    time_st  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_storetransaction PRIMARY KEY (id)
);

CREATE TABLE transaction_model
(
    uuid                     UUID NOT NULL,
    author_id                INTEGER,
    card_id                  INTEGER,
    image_generated_at       TIMESTAMP WITHOUT TIME ZONE,
    description_generated_at TIMESTAMP WITHOUT TIME ZONE,
    stats_generated_at       TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_transactionmodel PRIMARY KEY (uuid)
);

CREATE TABLE user_model
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    login     VARCHAR(255),
    pwd       VARCHAR(255),
    account   FLOAT                                    NOT NULL,
    last_name VARCHAR(255),
    sur_name  VARCHAR(255),
    email     VARCHAR(255),
    CONSTRAINT pk_usermodel PRIMARY KEY (id)
);

ALTER TABLE card_model
    ADD CONSTRAINT FK_CARDMODEL_ON_STORE FOREIGN KEY (store_id) REFERENCES store_transaction (id);

ALTER TABLE card_model
    ADD CONSTRAINT FK_CARDMODEL_ON_USER FOREIGN KEY (user_id) REFERENCES user_model (id);

ALTER TABLE transaction_model
    ADD CONSTRAINT FK_TRANSACTIONMODEL_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES user_model (id);

ALTER TABLE transaction_model
    ADD CONSTRAINT FK_TRANSACTIONMODEL_ON_CARD FOREIGN KEY (card_id) REFERENCES card_model (id);