CREATE TABLE chat_history
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sender_id   INTEGER                                  NOT NULL,
    message     VARCHAR(255)                             NOT NULL,
    sent_at     TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    receiver_id INTEGER,
    CONSTRAINT pk_chathistory PRIMARY KEY (id)
);

ALTER TABLE chat_history
    ADD CONSTRAINT FK_CHATHISTORY_ON_RECEIVER FOREIGN KEY (receiver_id) REFERENCES user_model (id);

ALTER TABLE chat_history
    ADD CONSTRAINT FK_CHATHISTORY_ON_SENDER FOREIGN KEY (sender_id) REFERENCES user_model (id);