---
version: "3.9"


services:
  amq:
    image: apache/activemq-artemis:2.37.0
    environment:
      ARTEMIS_USER: 'asibackend1'
      ARTEMIS_PASSWORD: 'asibackend1'
    ports:
      - '61616:61616'
      - '8161:8161'
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: 'asibackend1'
      POSTGRES_PASSWORD: 'asibackend1'
      POSTGRES_DB: 'asibackend1'
    ports:
        - '5432:5432'
