services:
  amq:
    image: apache/activemq-artemis:2.37.0
    environment:
      ARTEMIS_USER: 'asibackend1'
      ARTEMIS_PASSWORD: 'asibackend1'
    ports:
      - '61616:61616'
      - '8161:8161'

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: 'asibackend1'
      POSTGRES_PASSWORD: 'asibackend1'
      POSTGRES_DB: 'asibackend1'
    ports:
      - '5432:5432'

  ollama:
    image: ollama/ollama:0.3.13
    volumes:
      - ollama:/root/.ollama
    ports:
      - '11434:11434'

  neural:
    image: registry.gitlab.com/js-asi2/asi2-resources/img-gene-neural-love-api:v1.1
    environment:
      external.iaimgapi.token: 'v1.efbf79561ed86ee2d279bc30fa72ff50b7ef25e0c879a0ffce5568f00cab6906'
    ports:
      - '8080:8080'

volumes:
  ollama: