spring:
  main:
    web-application-type: none
  artemis:
    broker-url: "tcp://localhost:61616"
    user: asibackend1
    password: asibackend1
    mode: native
logging:
  level:
    org:
      apache:
        hc:
          client5:
            http: DEBUG